Repository ember-cli/ember-cli-inject-live-reload, pull requests merged in 2018-10, with the labels that each got.

#58 Run test suite on TravisCI
  .travis.yml
  index.js
  package.json
  tests/inject-live-reload-test.js
  yarn.lock
Labels: internal

#59 package.json: Declare Node.js version requirements
  package.json
Labels: enhancement

#57 Add linting via ESLint
  .eslintrc.js
  .jshintrc
  .travis.yml
  index.js
  package.json
  yarn.lock
Labels: internal

#60 Drop support for Node 4
  .travis.yml
  package.json
Labels: breaking

#65 fix: syntax error in `dynamicScript`
  index.js
  tests/inject-live-reload-test.js
Labels: bug
